apiVersion: v1
kind: Service
metadata:
  name: citizen-registry-db
  namespace: citizen-registry
  labels:
    app.kubernetes.io/name: citizen-registry-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: citizen-registry-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: citizen-registry-db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
