apiVersion: v1
kind: Secret
metadata:
  name: citizen-registry-db-secret
  namespace: citizen-registry
  labels:
    app.kubernetes.io/name: citizen-registry-db
    app.kubernetes.io/part-of: citizen-registry-backend
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass123
  MYSQL_DATABASE: citizens_registry
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass
