apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: citizen-registry-db-data
  namespace: citizen-registry
  labels:
    app.kubernetes.io/name: citizen-registry-db
    app.kubernetes.io/part-of: citizen-registry-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
